blueprint:
  name: Switch Control for Two Lights with Brightness
  description: Controls two lights using a ZHA remote switch with four buttons. Single press - Left top turns on first light, left bottom turns off first light, right top turns on second light, right bottom turns off second light. Double press - Left top increases brightness of first light, left bottom decreases, right top increases second light, right bottom decreases.
  domain: automation
  input:
    remote:
      name: Remote Switch
      description: The ZHA remote device to use.
      selector:
        device:
          integration: zha
    light_one:
      name: First Light
      description: The first light entity to control (left buttons).
      selector:
        target:
          entity:
            domain: light
    light_two:
      name: Second Light
      description: The second light entity to control (right buttons).
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step Percentage
      description: The percentage to increase or decrease brightness on double press (e.g., 10 for 10%).
      default: 25
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

trigger:
  - device_id: !input remote
    domain: zha
    type: remote_button_short_press
    subtype: Button 1 (Up)
    id: left_top
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_short_press
    subtype: Button 1 (Down)
    id: left_bottom
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_short_press
    subtype: Button 2 (Up)
    id: right_top
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_short_press
    subtype: Button 2 (Down)
    id: right_bottom
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_double_press
    subtype: Button 1 (Up)
    id: left_top_double
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_double_press
    subtype: Button 1 (Down)
    id: left_bottom_double
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_double_press
    subtype: Button 2 (Up)
    id: right_top_double
    trigger: device
  - device_id: !input remote
    domain: zha
    type: remote_button_double_press
    subtype: Button 2 (Down)
    id: right_bottom_double
    trigger: device

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: left_top
        sequence:
          - service: light.turn_on
            target: !input light_one
      - conditions:
          - condition: trigger
            id: left_bottom
        sequence:
          - service: light.turn_off
            target: !input light_one
      - conditions:
          - condition: trigger
            id: right_top
        sequence:
          - service: light.turn_on
            target: !input light_two
      - conditions:
          - condition: trigger
            id: right_bottom
        sequence:
          - service: light.turn_off
            target: !input light_two
      - conditions:
          - condition: trigger
            id: left_top_double
        sequence:
          - service: light.turn_on
            target: !input light_one
            data:
              brightness_step_pct: !input brightness_step
      - conditions:
          - condition: trigger
            id: left_bottom_double
        sequence:
          - service: light.turn_on
            target: !input light_one
            data:
              brightness_step_pct: "{{ -1 * brightness_step }}"
      - conditions:
          - condition: trigger
            id: right_top_double
        sequence:
          - service: light.turn_on
            target: !input light_two
            data:
              brightness_step_pct: !input brightness_step
      - conditions:
          - condition: trigger
            id: right_bottom_double
        sequence:
          - service: light.turn_on
            target: !input light_two
            data:
              brightness_step_pct: "{{ -1 * brightness_step }}"

mode: single
